#!/bin/zsh

if [ -n "$UPDATE_DOTFILE_REPO" ]; then
	remotes=$(vcsh "$UPDATE_DOTFILE_REPO" remote -v \
		| grep '\(fetch\)')
	for remote in $remotes; do
		remote_name="$(echo $remote | awk '{print $1}')"
		remote_url="$(echo $remote | awk '{print $2}')"
		if [[ "$remote_url" == http* ]]; then
			vcsh "$UPDATE_DOTFILE_REPO" remote update $remote_name
		else
			# Probably an SSH remote, check for SSH agent
			if [[ -n "$SSH_AUTH_SOCK" ]]; then
				vcsh "$UPDATE_DOTFILE_REPO" remote update $remote
			fi
		fi
	done
	local_head =$(vcsh "$UPDATE_DOTFILE_REPO" rev-parse @)
	remote_head=$(vcsh "$UPDATE_DOTFILE_REPO" rev-parse @{u})
	if ! [[ "$remote_head" == "$local_head" ]]; then
		echo "Configuration files are out of date.";
	fi
fi

[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm" # Load RVM into a shell session *as a function*
