#!/bin/sh
# Combined from ek9s granular scripts for easier checkout
git config core.sparseCheckout true
cat >> $GIT_DIR/info/sparse-checkout << EOF
*
!.gitignore
!LICENSE
!LICENSE.md
!LICENSE.txt
!README
!README.md
!README.txt
!Dockerfile
!Dockerfile*
!circle.yml
!.travis.yml
!vcsh-bootstrap.sh
!sparse_checkout_staging.sh
EOF
